# Generated by Django 2.1.3 on 2018-11-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_working_on_task', models.CharField(blank=True, max_length=20)),
                ('number_of_times_served', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=None, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('game_state', models.TextField(blank=True, default=None)),
                ('sigma_game_state', models.TextField(blank=True, default=None)),
                ('question_to_ask', models.TextField(blank=True, default=None)),
                ('breed', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionasking.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='traits',
            field=models.ManyToManyField(to='questionasking.Trait'),
        ),
    ]
