# Generated by Django 2.1.3 on 2018-11-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='errors',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
