# Generated by Django 2.1.3 on 2018-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0002_auto_20181108_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='errors',
            field=models.IntegerField(default=4.5, null=True),
        ),
    ]
