# Generated by Django 2.1.3 on 2018-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0004_auto_20181108_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='game_state',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='question_to_ask',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='sigma_game_state',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_working_on_task',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
