# Generated by Django 2.1.3 on 2018-11-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0006_auto_20181114_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='breed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionasking.Breed'),
        ),
        migrations.AlterField(
            model_name='image',
            name='game_state',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='question_set',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='sigma_game_state',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
