# Generated by Django 2.1.3 on 2018-11-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0007_auto_20181114_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_working_on_task',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
