# Generated by Django 2.1.3 on 2018-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0008_auto_20181114_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='question_set_constraint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='question_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
