# Generated by Django 2.1.3 on 2018-11-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionasking', '0009_auto_20181114_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='breed_dictionary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='trait_breed_matrix',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='trait_dictionary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='errors',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
